openapi: 3.0.0
info:
  title: Asteroid Query API
  version: 1.0.0
servers:
  - url: [END POINT DA SUA APLICAÇÃO QUE RECEBE E PROCESSA AS QUESTÕES DO USUÁRIO. SE FOR DO CLOUD FUNCTIONS, USE A URL FORNECIDA]  
paths:
  /playbook:
    post:
      summary: Responder perguntas sobre asteróides
      operationId: answerAsteroidQuestion
      requestBody:
        description: Questão sobre asteróides
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: A questão do user sobre asteróides
              required:
                - question
      responses:
        '200':
          description: "Get OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: Resposta da pergunta
        '400':
          description: "Get Erro"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: "Internal server error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
